insert into izdelek (ime, cena, opis) values ('Ecolab - Medallion', '28.97', 'Excision of Inferior Mesenteric Vein, Open Approach');
insert into izdelek (ime, cena, opis) values ('Food Colouring - Green', '45.31', 'Destruction of Right Thorax Bursa and Ligament, Open Approach');
insert into izdelek (ime, cena, opis) values ('Spinach - Packaged', '33.59', 'Drainage of Left Lacrimal Duct, Open Approach');
insert into izdelek (ime, cena, opis) values ('Grapes - Green', '36.65', 'Fragmentation in Anus, Via Natural or Artificial Opening');
insert into izdelek (ime, cena, opis) values ('Cocoa Butter', '43.80', 'Drainage of Azygos Vein with Drainage Device, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Grouper - Fresh', '33.15', 'Dilation of Left Femoral Artery with Four or More Intraluminal Devices, Open Approach');
insert into izdelek (ime, cena, opis) values ('Lid - Translucent, 3.5 And 6 Oz', '34.51', 'Restriction of Upper Vein with Intraluminal Device, Open Approach');
insert into izdelek (ime, cena, opis) values ('Vodka - Lemon, Absolut', '38.43', 'Revision of Internal Fixation Device in Left Upper Femur, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Tortillas - Flour, 12', '19.42', 'Computerized Tomography (CT Scan) of Left Upper Extremity using Low Osmolar Contrast');
insert into izdelek (ime, cena, opis) values ('Bouillion - Fish', '39.75', 'Dilation of Small Intestine with Intraluminal Device, Via Natural or Artificial Opening Endoscopic');
insert into izdelek (ime, cena, opis) values ('Pepper - Black, Crushed', '38.98', 'Revision of Radioactive Element in Mediastinum, Open Approach');
insert into izdelek (ime, cena, opis) values ('Octopus', '40.62', 'Resection of Left Lower Lung Lobe, Open Approach');
insert into izdelek (ime, cena, opis) values ('Ezy Change Mophandle', '16.41', 'Repair Left Subclavian Vein, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Sobe - Cranberry Grapefruit', '8.68', 'Extirpation of Matter from Large Intestine, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Bread Base - Toscano', '42.51', 'Release Left Atrium, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Soup - Campbells Mac N Cheese', '47.83', 'Removal of Nonautologous Tissue Substitute from Occipital-cervical Joint, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Bread - Pain Au Liat X12', '42.86', 'Repair Right Vas Deferens, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Bread - Focaccia Quarter', '20.66', 'Bypass Right Common Iliac Artery to Left Renal Artery, Open Approach');
insert into izdelek (ime, cena, opis) values ('Muffin - Zero Transfat', '2.93', 'Drainage of Left Pelvic Bone, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Pie Shells 10', '0.97', 'Alteration of Left Upper Leg, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Coconut - Whole', '43.92', 'Drainage of Left Internal Jugular Vein, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Onions Granulated', '23.27', 'Fragmentation in Peritoneal Cavity, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Guinea Fowl', '16.61', 'Bypass Left External Jugular Vein to Upper Vein with Nonautologous Tissue Substitute, Open Approach');
insert into izdelek (ime, cena, opis) values ('Sauce - White, Mix', '26.79', 'Supplement Duodenum with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Lamb - Leg, Diced', '34.88', 'Drainage of Lower Lip, Open Approach, Diagnostic');
insert into izdelek (ime, cena, opis) values ('Spice - Onion Powder Granulated', '49.92', 'Plaque Radiation of Chest Skin');
insert into izdelek (ime, cena, opis) values ('Juice - Apple, 341 Ml', '10.67', 'Drainage of Left Popliteal Artery, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Beer - Camerons Cream Ale', '26.19', 'Extirpation of Matter from Left Internal Iliac Artery, Bifurcation, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Smirnoff Green Apple Twist', '1.39', 'Resection of Left Lung, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Eggs - Extra Large', '45.45', 'Bypass Right Ureter to Ileum with Autologous Tissue Substitute, Open Approach');
insert into izdelek (ime, cena, opis) values ('Temperature Recording Station', '42.70', 'Destruction of Cervical Vertebra, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Pastry - Mini French Pastries', '20.11', 'Reposition Left Testis, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Pasta - Cappellini, Dry', '14.95', 'Occlusion of Middle Colic Artery with Intraluminal Device, Open Approach');
insert into izdelek (ime, cena, opis) values ('Chicken - White Meat With Tender', '11.27', 'Beam Radiation of Hypopharynx using Electrons');
insert into izdelek (ime, cena, opis) values ('Steampan Lid', '49.22', 'Replacement of Left Palatine Bone with Autologous Tissue Substitute, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Bread - Assorted Rolls', '31.64', 'Drainage of Lumbar Plexus, Percutaneous Approach, Diagnostic');
insert into izdelek (ime, cena, opis) values ('Beer - Fruli', '23.14', 'Insertion of Intramedullary Internal Fixation Device into Right Humeral Shaft, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Napkin White - Starched', '37.78', 'Supplement Right Metacarpocarpal Joint with Autologous Tissue Substitute, Open Approach');
insert into izdelek (ime, cena, opis) values ('Gelatine Leaves - Envelopes', '3.84', 'Removal of Infusion Device from Left Finger Phalangeal Joint, External Approach');
insert into izdelek (ime, cena, opis) values ('Table Cloth 54x54 Colour', '49.41', 'Revision of Internal Fixation Device in Left Toe Phalanx, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Lid Tray - 12in Dome', '27.96', 'Inspection of Pleura, Open Approach');
insert into izdelek (ime, cena, opis) values ('Table Cloth 53x69 White', '37.65', 'Insertion of Other Device into Chest Wall, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Trout - Rainbow, Fresh', '29.12', 'Division of Thoracic Vertebra, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Croissant, Raw - Mini', '25.33', 'Computerized Tomography (CT Scan) of Superior Mesenteric Artery using Low Osmolar Contrast');
insert into izdelek (ime, cena, opis) values ('Shrimp - 16/20, Peeled Deviened', '47.60', 'Replacement of Right Popliteal Artery with Synthetic Substitute, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Flax Seed', '45.35', 'Bypass Gallbladder to Stomach with Intraluminal Device, Open Approach');
insert into izdelek (ime, cena, opis) values ('Southern Comfort', '2.78', 'Replacement of Right Trunk Tendon with Synthetic Substitute, Open Approach');
insert into izdelek (ime, cena, opis) values ('Beef Ground Medium', '31.68', 'Reposition Left Kidney Pelvis, Open Approach');
insert into izdelek (ime, cena, opis) values ('Bagel - Plain', '23.44', 'Insertion of Tissue Expander into Left Upper Leg Subcutaneous Tissue and Fascia, Open Approach');
insert into izdelek (ime, cena, opis) values ('Wine - White, Mosel Gold', '36.47', 'Gastrointestinal System, Division');
insert into izdelek (ime, cena, opis) values ('Appetizer - Veg Assortment', '48.77', 'Reposition Right Breast, Open Approach');
insert into izdelek (ime, cena, opis) values ('Wine - Prem Select Charddonany', '37.20', 'Removal of Drainage Device from Lower Vein, External Approach');
insert into izdelek (ime, cena, opis) values ('Hand Towel', '9.15', 'Release Right Kidney, Open Approach');
insert into izdelek (ime, cena, opis) values ('Tortillas - Flour, 10', '37.43', 'Removal of Drainage Device from Left Shoulder Joint, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Grapes - Black', '49.27', 'Destruction of Left Upper Leg Skin, Multiple, External Approach');
insert into izdelek (ime, cena, opis) values ('Wine - Savigny - Les - Beaune', '42.85', 'Bypass Left Fallopian Tube to Uterus, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Rice - Sushi', '14.00', 'Division of Basal Ganglia, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Bread - Pumpernickle, Rounds', '0.03', 'Insertion of Intraluminal Device into Anus, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Bread - Pumpernickel', '8.34', 'Insertion of Radioactive Element into Male Perineum, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Lemon Grass', '26.07', 'Dilation of Left Anterior Tibial Artery, Bifurcation, with Drug-eluting Intraluminal Device, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Langers - Mango Nectar', '49.12', 'Muscle Performance Treatment of Musculoskeletal System - Lower Back / Lower Extremity using Assistive, Adaptive, Supportive or Protective Equipment');
insert into izdelek (ime, cena, opis) values ('Muffin - Mix - Creme Brule 15l', '17.15', 'Conditioned Play Audiometry Assessment');
insert into izdelek (ime, cena, opis) values ('Canada Dry', '15.68', 'Restriction of Cecum with Intraluminal Device, Open Approach');
insert into izdelek (ime, cena, opis) values ('Mustard - Pommery', '29.87', 'Supplement Left Hand with Autologous Tissue Substitute, Open Approach');
insert into izdelek (ime, cena, opis) values ('Pork - Loin, Bone - In', '23.17', 'Drainage of Left Lacrimal Bone, Percutaneous Approach, Diagnostic');
insert into izdelek (ime, cena, opis) values ('Sproutsmustard Cress', '9.36', 'Bypass Right Ureter to Right Ureter with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Ham - Cooked Italian', '15.99', 'Introduction of Immunosuppressive into Peripheral Artery, Open');
insert into izdelek (ime, cena, opis) values ('Irish Cream - Baileys', '28.28', 'Insertion of Intraluminal Device into Right Peroneal Artery, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Gherkin', '0.28', 'Drainage of Right Knee Region, Open Approach');
insert into izdelek (ime, cena, opis) values ('Beets', '31.21', 'Revision of Infusion Device in Lower Intestinal Tract, External Approach');
insert into izdelek (ime, cena, opis) values ('Lamb - Shoulder, Boneless', '35.94', 'Excision of Hymen, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Wine - Saint Emilion Calvet', '48.35', 'Destruction of Sacral Nerve, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Veal - Brisket, Provimi,bnls', '24.17', 'Aphasia Assessment using Augmentative / Alternative Communication Equipment');
insert into izdelek (ime, cena, opis) values ('Lemonade - Black Cherry, 591 Ml', '12.55', 'Division of Right Lower Leg Subcutaneous Tissue and Fascia, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Pie Shells 10', '48.12', 'Dilation of Middle Colic Artery, Bifurcation, with Three Drug-eluting Intraluminal Devices, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Lemon Grass', '17.47', 'Dilation of Coronary Artery, One Artery, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Apples - Sliced / Wedge', '0.29', 'Excision of Right Wrist Bursa and Ligament, Open Approach');
insert into izdelek (ime, cena, opis) values ('Wine - Montecillo Rioja Crianza', '0.64', 'Removal of Infusion Device from Pancreatic Duct, Via Natural or Artificial Opening Endoscopic');
insert into izdelek (ime, cena, opis) values ('Muffin Carrot - Individual', '45.44', 'Destruction of Peroneal Nerve, Open Approach');
insert into izdelek (ime, cena, opis) values ('Anisette - Mcguiness', '43.83', 'Insertion of Internal Fixation Device into Left Sphenoid Bone, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Mushroom Morel Fresh', '6.51', 'Drainage of Skull, Open Approach');
insert into izdelek (ime, cena, opis) values ('Wine - Barolo Fontanafredda', '11.93', 'Anatomical Regions, General, Transplantation');
insert into izdelek (ime, cena, opis) values ('Lid - 0090 Clear', '13.83', 'Extirpation of Matter from Thoracic Aorta, Descending, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Lobster - Tail, 3 - 4 Oz', '48.84', 'Bypass Cerebral Ventricle to Cerebral Cisterns with Synthetic Substitute, Open Approach');
insert into izdelek (ime, cena, opis) values ('Red Pepper Paste', '17.79', 'Removal of Monitoring Device from Bladder, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Vermouth - Sweet, Cinzano', '22.61', 'Drainage of Left Ovary, Open Approach');
insert into izdelek (ime, cena, opis) values ('Transfer Sheets', '39.37', 'Replacement of Left Upper Eyelid with Nonautologous Tissue Substitute, Open Approach');
insert into izdelek (ime, cena, opis) values ('Yogurt - Assorted Pack', '42.27', 'Bypass Left Femoral Artery to Posterior Tibial Artery with Autologous Venous Tissue, Open Approach');
insert into izdelek (ime, cena, opis) values ('Lettuce - Romaine, Heart', '45.05', 'Bypass Ileum to Rectum, Open Approach');
insert into izdelek (ime, cena, opis) values ('Sprouts - Bean', '22.30', 'Bypass Right Vas Deferens to Right Vas Deferens with Nonautologous Tissue Substitute, Open Approach');
insert into izdelek (ime, cena, opis) values ('Wine - Lou Black Shiraz', '44.54', 'Occlusion of Abdominal Aorta with Intraluminal Device, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Foil Cont Round', '7.93', 'Bypass Right Subclavian Artery to Left Upper Leg Artery with Autologous Venous Tissue, Open Approach');
insert into izdelek (ime, cena, opis) values ('Wine - Toasted Head', '31.68', 'Irrigation of Biliary and Pancreatic Tract using Irrigating Substance, Via Natural or Artificial Opening Endoscopic');
insert into izdelek (ime, cena, opis) values ('Wine - Domaine Boyar Royal', '12.20', 'Extracorporeal Therapies, Physiological Systems, Phototherapy');
insert into izdelek (ime, cena, opis) values ('Piping - Bags Quizna', '4.68', 'Nuclear Medicine, Lymphatic and Hematologic System, Planar Nuclear Medicine Imaging');
insert into izdelek (ime, cena, opis) values ('Numi - Assorted Teas', '45.91', 'Occlusion of Left Lower Lobe Bronchus, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Tea - Camomele', '41.33', 'Dilation of Left Renal Artery with Two Drug-eluting Intraluminal Devices, Open Approach');
insert into izdelek (ime, cena, opis) values ('Cornish Hen', '25.89', 'Revision of Synthetic Substitute in Nose, External Approach');
insert into izdelek (ime, cena, opis) values ('Sole - Fillet', '48.78', 'Occlusion of Right Brachial Vein with Extraluminal Device, Open Approach');
insert into izdelek (ime, cena, opis) values ('Nectarines', '0.60', 'Drainage of Coccygeal Glomus, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Evaporated Milk - Skim', '17.71', 'Dilation of Innominate Artery with Two Intraluminal Devices, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Mushroom - Enoki, Fresh', '45.13', 'Revision of Synthetic Substitute in Left Glenoid Cavity, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Irish Cream - Baileys', '47.65', 'Occlusion of Stomach with Intraluminal Device, Open Approach');
insert into izdelek (ime, cena, opis) values ('Vinegar - Champagne', '32.69', 'Insertion of Radioactive Element into Tracheobronchial Tree, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Water - Green Tea Refresher', '31.83', 'Occlusion of Right Common Iliac Vein, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Carbonated Water - Peach', '7.74', 'Removal of Radioactive Element from Head and Neck Subcutaneous Tissue and Fascia, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Cream - 18%', '47.61', 'Alteration of Face with Synthetic Substitute, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Apple - Delicious, Golden', '12.92', 'Excision of Left Wrist Region, Percutaneous Endoscopic Approach, Diagnostic');
insert into izdelek (ime, cena, opis) values ('Onions - Pearl', '37.70', 'Supplement Left Ankle Bursa and Ligament with Synthetic Substitute, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Bread - Sour Batard', '8.44', 'Extirpation of Matter from Cranial Cavity, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Ostrich - Prime Cut', '29.09', 'Reposition Right Ulna with Monoplanar External Fixation Device, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Allspice - Jamaican', '20.27', 'Fusion of Occipital-cervical Joint with Synthetic Substitute, Anterior Approach, Anterior Column, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Tuna - Fresh', '27.57', 'Removal of Autologous Tissue Substitute from Right Tibia, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Wine - Prem Select Charddonany', '24.27', 'Removal of Drainage Device from Nasal Bone, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Cilantro / Coriander - Fresh', '0.13', 'Supplement Trochlear Nerve with Autologous Tissue Substitute, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Corn Syrup', '43.07', 'Supplement Right Shoulder Bursa and Ligament with Nonautologous Tissue Substitute, Open Approach');
insert into izdelek (ime, cena, opis) values ('Banana Turning', '6.61', 'Drainage of Left Shoulder Tendon with Drainage Device, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Vinegar - Red Wine', '41.14', 'Removal of Spacer from Left Carpal Joint, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Bread Crumbs - Panko', '17.57', 'Removal of Infusion Device from Lower Artery, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Kiwi', '17.23', 'Bypass Abdominal Aorta to Left Internal Iliac Artery with Synthetic Substitute, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Pepper - White, Whole', '12.61', 'Removal of Nonautologous Tissue Substitute from Thoracic Vertebra, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Chocolate - Chips Compound', '22.55', 'Removal of Infusion Device from Lumbosacral Joint, External Approach');
insert into izdelek (ime, cena, opis) values ('Butter Ripple - Phillips', '49.07', 'Supplement Left Peroneal Artery with Nonautologous Tissue Substitute, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Tomatoes - Grape', '24.45', 'Drainage of Nasopharynx, Via Natural or Artificial Opening, Diagnostic');
insert into izdelek (ime, cena, opis) values ('Bread Sour Rolls', '46.02', 'Dilation of Coronary Artery, Three Arteries with Radioactive Intraluminal Device, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Cup - 6oz, Foam', '4.82', 'Resection of Right Zygomatic Bone, Open Approach');
insert into izdelek (ime, cena, opis) values ('Soup - Clam Chowder, Dry Mix', '41.68', 'Magnetic Resonance Imaging (MRI) of Thyroid Gland using Other Contrast, Unenhanced and Enhanced');
insert into izdelek (ime, cena, opis) values ('Shichimi Togarashi Peppeers', '37.62', 'Removal of Nonautologous Tissue Substitute from Cervicothoracic Vertebral Joint, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Aspic - Clear', '42.79', 'High Dose Rate (HDR) Brachytherapy of Liver using Iodine 125 (I-125)');
insert into izdelek (ime, cena, opis) values ('Wine - Touraine Azay - Le - Rideau', '23.30', 'Drainage of Hymen with Drainage Device, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Bread - Wheat Baguette', '7.90', 'Extirpation of Matter from Left Upper Arm Tendon, Open Approach');
insert into izdelek (ime, cena, opis) values ('Horseradish - Prepared', '29.86', 'Revision of Autologous Tissue Substitute in Peritoneum, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Olives - Stuffed', '46.34', 'Removal of Nonautologous Tissue Substitute from Upper Jaw, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Straws - Cocktale', '19.86', 'Tomographic (Tomo) Nuclear Medicine Imaging of Pelvic Region using Other Radionuclide');
insert into izdelek (ime, cena, opis) values ('Cucumber - Pickling Ontario', '4.18', 'Dilation of Left Temporal Artery, Bifurcation, with Three Intraluminal Devices, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Wine - Cotes Du Rhone', '49.47', 'Bypass Innominate Artery to Left Lower Arm Artery with Autologous Venous Tissue, Open Approach');
insert into izdelek (ime, cena, opis) values ('Cheese - Wine', '11.99', 'Monaural Electroacoustic Hearing Aid Check Assessment');
insert into izdelek (ime, cena, opis) values ('Rum - Spiced, Captain Morgan', '34.22', 'Supplement Left Ventricle with Synthetic Substitute, Open Approach');
insert into izdelek (ime, cena, opis) values ('Wine - Mondavi Coastal Private', '6.84', 'Revision of Drainage Device in Thoracolumbar Vertebral Joint, Open Approach');
insert into izdelek (ime, cena, opis) values ('Cake - Cheese Cake 9 Inch', '4.66', 'Transfer Right Ankle Tendon, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Jolt Cola - Electric Blue', '49.15', 'Destruction of Perineum Muscle, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Soap - Pine Sol Floor Cleaner', '40.09', 'Drainage of Urethra, Via Natural or Artificial Opening Endoscopic, Diagnostic');
insert into izdelek (ime, cena, opis) values ('Wine - Zinfandel Rosenblum', '9.84', 'Extirpation of Matter from Left Pleura, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Wine - Chardonnay Mondavi', '10.86', 'Drainage of Left Ureter with Drainage Device, Via Natural or Artificial Opening');
insert into izdelek (ime, cena, opis) values ('Pancetta', '28.51', 'Revision of Radioactive Element in Neck, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Wine La Vielle Ferme Cote Du', '45.86', 'Removal of Nonautologous Tissue Substitute from Right Sacroiliac Joint, Percutaneous Approach');
insert into izdelek (ime, cena, opis) values ('Oyster - In Shell', '28.12', 'Replacement of Left Metacarpal with Nonautologous Tissue Substitute, Open Approach');
insert into izdelek (ime, cena, opis) values ('Wine - White, Pinot Grigio', '28.91', 'Bypass Left Internal Jugular Vein to Upper Vein with Autologous Arterial Tissue, Open Approach');
insert into izdelek (ime, cena, opis) values ('Mushrooms - Black, Dried', '27.82', 'Removal of Synthetic Substitute from Tracheobronchial Tree, Percutaneous Endoscopic Approach');
insert into izdelek (ime, cena, opis) values ('Bread Crumbs - Panko', '29.65', 'Drainage of Paraganglion Extremity, Percutaneous Approach');
